export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/etc/Caskroom"
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

#python stuff
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/src
source /usr/local/bin/virtualenvwrapper.sh

#aliases
alias pushlive='git push live master'
